-- Generated from src/data/client-platform-listings.json.
-- Re-running this file is safe: seeded properties, facilities and rental options
-- are updated by their natural keys. Uploaded media is not touched.
-- Transit travel times are 10-minute walking placeholders from the source JSON.
-- Availability is initially set to available because no live inventory status was supplied.

begin;

insert into public.properties (
  slug,
  title,
  description,
  property_type,
  managed_by,
  city,
  area,
  state,
  status,
  is_featured,
  transit_connections,
  published_at,
  updated_at
)
values
  ('the-zizz', 'The Zizz', 'Fully furnished RentDeer rooms at The Zizz, covering the Cosmo and Divo residences in Damansara Damai.', 'Managed residence', 'RentDeer Property Management', 'Petaling Jaya', 'Damansara Damai', 'Selangor', 'published', false, '[{"stationId":"damansara-damai-mrt","accessMinutes":10,"accessMode":"walk"},{"stationId":"sungai-buloh-mrt","accessMinutes":10,"accessMode":"walk"}]'::jsonb, now(), now()),
  ('residensi-suasana-damai', 'Residensi Suasana @ Damai', 'Fully furnished RentDeer rooms at Residensi Suasana @ Damai in Damansara Damai.', 'Managed residence', 'RentDeer Property Management', 'Petaling Jaya', 'Damansara Damai', 'Selangor', 'published', false, '[{"stationId":"damansara-damai-mrt","accessMinutes":10,"accessMode":"walk"},{"stationId":"sungai-buloh-mrt","accessMinutes":10,"accessMode":"walk"}]'::jsonb, now(), now()),
  ('unio-residence-kepong', 'Unio Residence, Kepong', 'Fully furnished RentDeer rooms at Unio Residence in Kepong.', 'Managed residence', 'RentDeer Property Management', 'Kuala Lumpur', 'Kepong', 'Kuala Lumpur', 'published', false, '[{"stationId":"kepong-mrt","accessMinutes":10,"accessMode":"walk"},{"stationId":"jinjang-mrt","accessMinutes":10,"accessMode":"walk"}]'::jsonb, now(), now()),
  ('pixel-city-sentral', 'Pixel City Sentral Residence', 'Fully furnished RentDeer rooms at Pixel City Sentral in Bandar Sri Permaisuri.', 'Managed residence', 'RentDeer Property Management', 'Kuala Lumpur', 'Bandar Sri Permaisuri', 'Kuala Lumpur', 'published', false, '[{"stationId":"salak-selatan-lrt","accessMinutes":10,"accessMode":"walk"},{"stationId":"salak-selatan-ktm","accessMinutes":10,"accessMode":"walk"}]'::jsonb, now(), now()),
  ('aratre-residences', 'AraTre’ Residences', 'Fully furnished RentDeer rooms at AraTre’ Residences in Ara Damansara.', 'Managed residence', 'RentDeer Property Management', 'Petaling Jaya', 'Ara Damansara', 'Selangor', 'published', false, '[{"stationId":"ara-damansara-lrt","accessMinutes":10,"accessMode":"walk"},{"stationId":"glenmarie-lrt","accessMinutes":10,"accessMode":"walk"}]'::jsonb, now(), now()),
  ('high-park-suites', 'High Park Suites', 'Fully furnished rooms and private studio options at High Park Suites in Kelana Jaya.', 'Managed residence and studio', 'RentDeer Property Management', 'Petaling Jaya', 'Kelana Jaya', 'Selangor', 'published', false, '[{"stationId":"taman-bahagia-lrt","accessMinutes":10,"accessMode":"walk"},{"stationId":"glenmarie-lrt","accessMinutes":10,"accessMode":"walk"}]'::jsonb, now(), now()),
  ('emporis-kota-damansara', 'Emporis, Kota Damansara', 'Fully furnished RentDeer rooms at Emporis in Kota Damansara.', 'Managed residence', 'RentDeer Property Management', 'Petaling Jaya', 'Kota Damansara', 'Selangor', 'published', false, '[{"stationId":"kota-damansara-mrt","accessMinutes":10,"accessMode":"walk"},{"stationId":"kwasa-sentral-mrt","accessMinutes":10,"accessMode":"walk"}]'::jsonb, now(), now()),
  ('meta-residence-seri-kembangan', 'Meta Residence', 'Fully furnished rooms, SOHO and whole-unit options at Meta Residence in Seri Kembangan.', 'Managed residence, SOHO and whole unit', 'RentDeer Property Management', 'Seri Kembangan', 'Seri Kembangan', 'Selangor', 'published', false, '[{"stationId":"putra-permai-mrt","accessMinutes":10,"accessMode":"walk"},{"stationId":"equine-mrt","accessMinutes":10,"accessMode":"walk"}]'::jsonb, now(), now()),
  ('rica-residence-sentul', 'Rica Residence, Sentul', 'Fully furnished RentDeer rooms at Rica Residence in Sentul.', 'Managed residence', 'RentDeer Property Management', 'Kuala Lumpur', 'Sentul', 'Kuala Lumpur', 'published', false, '[{"stationId":"sentul-barat-mrt","accessMinutes":10,"accessMode":"walk"},{"stationId":"sentul-ktm","accessMinutes":10,"accessMode":"walk"}]'::jsonb, now(), now()),
  ('platinum-splendor-semarak', 'Platinum Splendor Residensi', 'Fully furnished RentDeer rooms at Platinum Splendor Residensi in Semarak.', 'Managed residence', 'RentDeer Property Management', 'Kuala Lumpur', 'Semarak', 'Kuala Lumpur', 'published', false, '[{"stationId":"raja-uda-mrt","accessMinutes":10,"accessMode":"walk"},{"stationId":"damai-lrt","accessMinutes":10,"accessMode":"walk"}]'::jsonb, now(), now())
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  property_type = excluded.property_type,
  managed_by = excluded.managed_by,
  city = excluded.city,
  area = excluded.area,
  state = excluded.state,
  status = excluded.status,
  is_featured = excluded.is_featured,
  transit_connections = excluded.transit_connections,
  published_at = coalesce(public.properties.published_at, excluded.published_at),
  updated_at = now();

insert into public.facilities (slug, name)
values
  ('swimming-pool', 'Swimming pool'),
  ('wading-pool', 'Wading pool'),
  ('gym-centre', 'Gym centre'),
  ('bbq-area', 'BBQ area'),
  ('surau', 'Surau'),
  ('24-hour-security', '24-hour security'),
  ('infinity-pool', 'Infinity pool'),
  ('outdoor-gym', 'Outdoor gym'),
  ('tennis-court', 'Tennis court'),
  ('badminton-court', 'Badminton court'),
  ('sky-lounge', 'Sky lounge'),
  ('business-centre', 'Business centre'),
  ('sauna', 'Sauna'),
  ('mini-mart', 'Mini mart'),
  ('laundry-room', 'Laundry room'),
  ('rooftop-level-28', 'Rooftop (Level 28)'),
  ('yoga-deck', 'Yoga deck'),
  ('jogging-track', 'Jogging track'),
  ('lounge', 'Lounge'),
  ('multi-purpose-hall', 'Multi-purpose hall'),
  ('jacuzzi', 'Jacuzzi'),
  ('multi-sport-court', 'Multi-sport court'),
  ('rooftop-terrace', 'Rooftop terrace'),
  ('sky-court', 'Sky court'),
  ('mini-store', 'Mini store'),
  ('bank', 'Bank'),
  ('reading-room', 'Reading room'),
  ('basketball-court', 'Basketball court'),
  ('trampoline-park-level-33a', 'Trampoline park (Level 33A)'),
  ('playground', 'Playground')
on conflict (slug) do update set name = excluded.name;

with facility_map(property_slug, facility_slug, sort_order) as (
  values
  ('the-zizz', 'swimming-pool', 0),
  ('the-zizz', 'wading-pool', 1),
  ('the-zizz', 'gym-centre', 2),
  ('the-zizz', 'bbq-area', 3),
  ('the-zizz', 'surau', 4),
  ('the-zizz', '24-hour-security', 5),
  ('residensi-suasana-damai', 'swimming-pool', 0),
  ('residensi-suasana-damai', 'wading-pool', 1),
  ('residensi-suasana-damai', 'gym-centre', 2),
  ('residensi-suasana-damai', 'bbq-area', 3),
  ('residensi-suasana-damai', 'surau', 4),
  ('residensi-suasana-damai', '24-hour-security', 5),
  ('unio-residence-kepong', 'infinity-pool', 0),
  ('unio-residence-kepong', 'outdoor-gym', 1),
  ('unio-residence-kepong', 'tennis-court', 2),
  ('unio-residence-kepong', 'badminton-court', 3),
  ('unio-residence-kepong', 'sky-lounge', 4),
  ('unio-residence-kepong', 'business-centre', 5),
  ('unio-residence-kepong', '24-hour-security', 6),
  ('pixel-city-sentral', 'swimming-pool', 0),
  ('pixel-city-sentral', 'wading-pool', 1),
  ('pixel-city-sentral', 'gym-centre', 2),
  ('pixel-city-sentral', 'sauna', 3),
  ('pixel-city-sentral', 'mini-mart', 4),
  ('pixel-city-sentral', 'laundry-room', 5),
  ('pixel-city-sentral', 'rooftop-level-28', 6),
  ('aratre-residences', 'swimming-pool', 0),
  ('aratre-residences', 'wading-pool', 1),
  ('aratre-residences', 'gym-centre', 2),
  ('aratre-residences', 'yoga-deck', 3),
  ('aratre-residences', 'jogging-track', 4),
  ('aratre-residences', 'lounge', 5),
  ('aratre-residences', 'multi-purpose-hall', 6),
  ('aratre-residences', '24-hour-security', 7),
  ('high-park-suites', 'swimming-pool', 0),
  ('high-park-suites', 'jacuzzi', 1),
  ('high-park-suites', 'sauna', 2),
  ('high-park-suites', 'multi-sport-court', 3),
  ('high-park-suites', 'rooftop-terrace', 4),
  ('high-park-suites', 'sky-court', 5),
  ('high-park-suites', 'business-centre', 6),
  ('high-park-suites', 'mini-store', 7),
  ('high-park-suites', 'bank', 8),
  ('emporis-kota-damansara', 'swimming-pool', 0),
  ('emporis-kota-damansara', 'reading-room', 1),
  ('emporis-kota-damansara', 'gym-centre', 2),
  ('emporis-kota-damansara', 'bbq-area', 3),
  ('emporis-kota-damansara', '24-hour-security', 4),
  ('emporis-kota-damansara', 'tennis-court', 5),
  ('emporis-kota-damansara', 'basketball-court', 6),
  ('meta-residence-seri-kembangan', 'swimming-pool', 0),
  ('meta-residence-seri-kembangan', 'gym-centre', 1),
  ('meta-residence-seri-kembangan', 'basketball-court', 2),
  ('meta-residence-seri-kembangan', 'bbq-area', 3),
  ('meta-residence-seri-kembangan', '24-hour-security', 4),
  ('rica-residence-sentul', 'swimming-pool', 0),
  ('rica-residence-sentul', 'gym-centre', 1),
  ('rica-residence-sentul', 'trampoline-park-level-33a', 2),
  ('rica-residence-sentul', 'multi-purpose-hall', 3),
  ('rica-residence-sentul', '24-hour-security', 4),
  ('platinum-splendor-semarak', 'swimming-pool', 0),
  ('platinum-splendor-semarak', 'wading-pool', 1),
  ('platinum-splendor-semarak', 'gym-centre', 2),
  ('platinum-splendor-semarak', 'bbq-area', 3),
  ('platinum-splendor-semarak', 'surau', 4),
  ('platinum-splendor-semarak', 'playground', 5),
  ('platinum-splendor-semarak', 'multi-purpose-hall', 6),
  ('platinum-splendor-semarak', '24-hour-security', 7)
)
insert into public.property_facilities (property_id, facility_id, sort_order)
select properties.id, facilities.id, facility_map.sort_order
from facility_map
join public.properties on properties.slug = facility_map.property_slug
join public.facilities on facilities.slug = facility_map.facility_slug
on conflict (property_id, facility_id) do update set
  sort_order = excluded.sort_order;

with rental_seed (
  property_slug,
  slug,
  title,
  internal_code,
  variant,
  room_type,
  description,
  price_min,
  price_max,
  price_note,
  bedrooms,
  bathrooms,
  bed_type,
  bathroom_type,
  furnished,
  availability,
  quantity_available,
  status,
  sort_order
) as (
  values
  ('the-zizz', 'cosmo-room-a', 'The Zizz (Cosmo) Room A', 'Room A', 'Cosmo', 'master_bedroom', 'Queen bed, fully furnished, private toilet.', 800, 850, 'RM800 - RM850', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 0),
  ('the-zizz', 'divo-room-a-master', 'The Zizz (Divo) Room A', 'Room A', 'Divo', 'master_bedroom', 'Queen bed, fully furnished, private toilet.', 800, 850, 'RM800 - RM850', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 1),
  ('the-zizz', 'cosmo-room-b', 'The Zizz (Cosmo) Room B', 'Room B', 'Cosmo', 'medium_bedroom', 'Single bed, fully furnished, shared toilet.', 600, 700, 'RM600 - RM700', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 2),
  ('the-zizz', 'cosmo-room-c', 'The Zizz (Cosmo) Room C', 'Room C', 'Cosmo', 'medium_bedroom', 'Single bed, fully furnished, shared toilet.', 650, null, 'RM650', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 3),
  ('the-zizz', 'divo-room-b', 'The Zizz (Divo) Room B', 'Room B', 'Divo', 'medium_bedroom', 'Single bed, fully furnished, shared toilet.', 550, null, 'RM550', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 4),
  ('the-zizz', 'divo-room-a-and-c', 'The Zizz (Divo) Room A & C', 'Room A & C', 'Divo', 'medium_bedroom', 'Single bed, fully furnished, shared toilet.', 650, null, 'RM650', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 5),
  ('the-zizz', 'cosmo-room-d', 'The Zizz (Cosmo) Room D', 'Room D', 'Cosmo', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 500, 600, 'RM500 - RM600', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 6),
  ('the-zizz', 'divo-room-d', 'The Zizz (Divo) Room D', 'Room D', 'Divo', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 500, 550, 'RM500 - RM550', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 7),
  ('the-zizz', 'cosmo-room-e', 'The Zizz (Cosmo) Room E', 'Room E', 'Cosmo', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 580, null, 'RM580', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 8),
  ('the-zizz', 'divo-room-e', 'The Zizz (Divo) Room E', 'Room E', 'Divo', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 400, 500, 'RM400 - RM500', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 9),
  ('residensi-suasana-damai', 'room-a-balcony', 'Residensi Suasana Room A (Balcony)', 'Room A', 'Balcony', 'master_bedroom', 'Queen bed, fully furnished, private toilet and balcony.', 900, null, 'RM900', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 0),
  ('residensi-suasana-damai', 'room-a-standard', 'Residensi Suasana Room A (Standard)', 'Room A', 'Standard', 'master_bedroom', 'Queen bed, fully furnished, private toilet and no balcony.', 850, null, 'RM850', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 1),
  ('residensi-suasana-damai', 'room-b-balcony', 'Residensi Suasana Room B (Balcony)', 'Room B', 'Balcony', 'medium_bedroom', 'Super single bed, fully furnished, shared toilet and balcony.', 680, null, 'RM680', 1, 1, 'Super single bed', 'shared', true, 'available', 1, 'published', 2),
  ('residensi-suasana-damai', 'room-b-standard', 'Residensi Suasana Room B (Standard)', 'Room B', 'Standard', 'medium_bedroom', 'Super single bed, fully furnished, shared toilet.', 650, 700, 'RM650 - RM700', 1, 1, 'Super single bed', 'shared', true, 'available', 1, 'published', 3),
  ('residensi-suasana-damai', 'room-c', 'Residensi Suasana Room C', 'Room C', '', 'medium_bedroom', 'Super single bed, fully furnished, shared toilet.', 650, 680, 'RM650 - RM680', 1, 1, 'Super single bed', 'shared', true, 'available', 1, 'published', 4),
  ('residensi-suasana-damai', 'room-d', 'Residensi Suasana Room D', 'Room D', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 580, 650, 'RM580 - RM650', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 5),
  ('residensi-suasana-damai', 'room-e', 'Residensi Suasana Room E', 'Room E', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 550, null, 'RM550', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 6),
  ('unio-residence-kepong', 'room-a', 'Unio Residence Room A', 'Room A', '', 'master_bedroom', 'Queen bed, fully furnished, private toilet.', 1000, 1100, 'RM1000 - RM1100', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 0),
  ('unio-residence-kepong', 'room-b-balcony', 'Unio Residence Room B (Balcony)', 'Room B', 'Balcony', 'medium_bedroom', 'Queen or single bed, fully furnished, shared toilet and balcony.', 850, 900, 'RM850 - RM900', 1, 1, 'Queen/single bed', 'shared', true, 'available', 1, 'published', 1),
  ('unio-residence-kepong', 'room-c-standard', 'Unio Residence Room C (Standard)', 'Room C', 'Standard', 'medium_bedroom', 'Queen or single bed, fully furnished, shared toilet.', 750, 800, 'RM750 - RM800', 1, 1, 'Queen/single bed', 'shared', true, 'available', 1, 'published', 2),
  ('unio-residence-kepong', 'room-d', 'Unio Residence Room D', 'Room D', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 600, null, 'RM600', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 3),
  ('pixel-city-sentral', 'room-a', 'Pixel City Sentral Room A', 'Room A', '', 'master_bedroom', 'Queen bed, fully furnished, private toilet.', 1250, null, 'RM1250', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 0),
  ('pixel-city-sentral', 'room-b', 'Pixel City Sentral Room B', 'Room B', '', 'master_bedroom', 'Queen bed, fully furnished, private toilet.', 1100, null, 'RM1100', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 1),
  ('pixel-city-sentral', 'room-c', 'Pixel City Sentral Room C', 'Room C', '', 'medium_bedroom', 'Queen or single bed, fully furnished, shared toilet.', 900, null, 'RM900', 1, 1, 'Queen/single bed', 'shared', true, 'available', 1, 'published', 2),
  ('pixel-city-sentral', 'room-d-medium', 'Pixel City Sentral Room D', 'Room D', 'Medium room', 'medium_bedroom', 'Queen or single bed, fully furnished, shared toilet.', 800, null, 'RM800', 1, 1, 'Queen/single bed', 'shared', true, 'available', 1, 'published', 3),
  ('pixel-city-sentral', 'room-d-single', 'Pixel City Sentral Room D', 'Room D', 'Single room', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 650, null, 'RM650; client source also names the medium option Room D', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 4),
  ('aratre-residences', 'room-a', 'AraTre’ Residences Room A', 'Room A', '', 'master_bedroom', 'Queen bed, fully furnished, private toilet.', 1250, null, 'RM1250', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 0),
  ('aratre-residences', 'room-b-balcony', 'AraTre’ Residences Room B (Balcony)', 'Room B', 'Balcony', 'medium_bedroom', 'Queen or single bed, fully furnished, shared toilet and balcony.', 900, 950, 'RM900 - RM950', 1, 1, 'Queen/single bed', 'shared', true, 'available', 1, 'published', 1),
  ('aratre-residences', 'room-c-standard', 'AraTre’ Residences Room C (Standard)', 'Room C', 'Standard', 'medium_bedroom', 'Queen or single bed, fully furnished, shared toilet.', 850, null, 'RM850', 1, 1, 'Queen/single bed', 'shared', true, 'available', 1, 'published', 2),
  ('aratre-residences', 'room-d', 'AraTre’ Residences Room D', 'Room D', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 750, null, 'RM750', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 3),
  ('aratre-residences', 'room-e', 'AraTre’ Residences Room E', 'Room E', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 750, null, 'RM750', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 4),
  ('high-park-suites', 'studio-a', 'High Park Suites (Studio A)', 'Studio A', '', 'soho_studio', 'Queen bed, fully furnished, private toilet, basic kitchen, washing machine and dryer.', 1600, null, 'RM1600', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 0),
  ('high-park-suites', 'studio-b', 'High Park Suites (Studio B)', 'Studio B', '', 'soho_studio', 'Queen bed, fully furnished, private toilet and basic kitchen.', 1500, null, 'RM1500', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 1),
  ('high-park-suites', 'room-a-and-b', 'High Park Suites Room A & B', 'Room A & B', '', 'medium_bedroom', 'Queen bed, fully furnished, shared toilet.', 950, null, 'RM950', 1, 1, 'Queen bed', 'shared', true, 'available', 1, 'published', 2),
  ('high-park-suites', 'room-c-medium', 'High Park Suites Room C', 'Room C', 'Medium room', 'medium_bedroom', 'Queen bed, fully furnished, shared toilet.', 800, null, 'RM800', 1, 1, 'Queen bed', 'shared', true, 'available', 1, 'published', 3),
  ('high-park-suites', 'room-c-single', 'High Park Suites Room C', 'Room C', 'Single room', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 750, null, 'RM750; client source also names the medium option Room C', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 4),
  ('emporis-kota-damansara', 'room-a', 'Emporis Room A', 'Room A', '', 'master_bedroom', 'Queen bed, fully furnished, private toilet.', 1300, 1500, 'RM1300 - RM1500', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 0),
  ('emporis-kota-damansara', 'room-b', 'Emporis Room B', 'Room B', '', 'medium_bedroom', 'Queen bed, fully furnished, private toilet.', 950, null, 'RM950', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 1),
  ('emporis-kota-damansara', 'room-c', 'Emporis Room C', 'Room C', '', 'medium_bedroom', 'Queen bed, fully furnished, private toilet.', 900, 950, 'RM900 - RM950', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 2),
  ('emporis-kota-damansara', 'room-d', 'Emporis Room D', 'Room D', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 650, 700, 'RM650 - RM700; earlier summary distinguishes window RM700 and no window RM650', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 3),
  ('meta-residence-seri-kembangan', 'soho', 'Meta Residence (SOHO)', 'SOHO', '', 'soho_studio', 'Queen bed, fully furnished, private toilet, kitchen, dryer and washing machine.', 1800, null, 'RM1800', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 0),
  ('meta-residence-seri-kembangan', 'whole-unit', 'Meta Residence (Whole Unit)', 'Whole Unit', '', 'whole_unit', 'Three bedrooms, two toilets, fully furnished, kitchen, dryer and washing machine.', 2200, null, 'RM2200', 3, 2, '', 'private', true, 'available', 1, 'published', 1),
  ('meta-residence-seri-kembangan', 'room-a', 'Meta Residence Room A', 'Room A', '', 'master_bedroom', 'Queen bed, fully furnished, private toilet.', 900, null, 'RM900', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 2),
  ('meta-residence-seri-kembangan', 'room-b', 'Meta Residence Room B', 'Room B', '', 'medium_bedroom', 'Queen or super single bed, fully furnished, shared toilet.', 650, 700, 'RM650 - RM700', 1, 1, 'Queen/super single bed', 'shared', true, 'available', 1, 'published', 3),
  ('meta-residence-seri-kembangan', 'room-c', 'Meta Residence Room C', 'Room C', '', 'medium_bedroom', 'Queen or super single bed, fully furnished, shared toilet.', 700, 750, 'RM700 - RM750', 1, 1, 'Queen/super single bed', 'shared', true, 'available', 1, 'published', 4),
  ('meta-residence-seri-kembangan', 'room-d', 'Meta Residence Room D', 'Room D', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 650, null, 'RM650', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 5),
  ('meta-residence-seri-kembangan', 'room-e', 'Meta Residence Room E', 'Room E', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 550, 580, 'RM550 - RM580', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 6),
  ('rica-residence-sentul', 'room-a', 'Rica Residence Room A', 'Room A', '', 'master_bedroom', 'Queen bed, fully furnished, private toilet.', 1000, 1200, 'RM1000 - RM1200', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 0),
  ('rica-residence-sentul', 'room-b', 'Rica Residence Room B', 'Room B', '', 'medium_bedroom', 'Queen or single bed, fully furnished, shared toilet.', 750, 1000, 'RM750 - RM1000', 1, 1, 'Queen/single bed', 'shared', true, 'available', 1, 'published', 1),
  ('rica-residence-sentul', 'room-c', 'Rica Residence Room C', 'Room C', '', 'medium_bedroom', 'Queen or single bed, fully furnished, shared toilet.', 800, 1000, 'RM800 - RM1000', 1, 1, 'Queen/single bed', 'shared', true, 'available', 1, 'published', 2),
  ('rica-residence-sentul', 'room-d', 'Rica Residence Room D', 'Room D', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 650, 700, 'RM650 - RM700', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 3),
  ('rica-residence-sentul', 'room-e', 'Rica Residence Room E', 'Room E', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 600, null, 'RM600', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 4),
  ('platinum-splendor-semarak', 'room-a', 'Platinum Splendor Residensi Room A', 'Room A', '', 'master_bedroom', 'Queen bed, fully furnished, private toilet.', 950, null, 'RM950', 1, 1, 'Queen bed', 'private', true, 'available', 1, 'published', 0),
  ('platinum-splendor-semarak', 'room-b-balcony', 'Platinum Splendor Residensi Room B (Balcony)', 'Room B', 'Balcony', 'medium_bedroom', 'Queen or single bed, fully furnished, shared toilet and balcony.', 800, null, 'RM800', 1, 1, 'Queen/single bed', 'shared', true, 'available', 1, 'published', 1),
  ('platinum-splendor-semarak', 'room-c-standard', 'Platinum Splendor Residensi Room C (Standard)', 'Room C', 'Standard', 'medium_bedroom', 'Queen or single bed, fully furnished, shared toilet.', 750, null, 'RM750', 1, 1, 'Queen/single bed', 'shared', true, 'available', 1, 'published', 2),
  ('platinum-splendor-semarak', 'room-d', 'Platinum Splendor Residensi Room D', 'Room D', '', 'single_bedroom', 'Single bed, fully furnished, shared toilet.', 650, null, 'RM650; photos pending', 1, 1, 'Single bed', 'shared', true, 'available', 1, 'published', 3)
)
insert into public.rental_options (
  property_id,
  slug,
  title,
  internal_code,
  variant,
  room_type,
  description,
  price_min,
  price_max,
  currency,
  price_note,
  bedrooms,
  bathrooms,
  area_sqft,
  bed_type,
  bathroom_type,
  furnished,
  availability,
  quantity_available,
  status,
  sort_order,
  published_at,
  updated_at
)
select
  properties.id,
  rental_seed.slug,
  rental_seed.title,
  nullif(rental_seed.internal_code, ''),
  nullif(rental_seed.variant, ''),
  rental_seed.room_type::public.room_type,
  rental_seed.description,
  rental_seed.price_min,
  rental_seed.price_max,
  'MYR',
  nullif(rental_seed.price_note, ''),
  rental_seed.bedrooms,
  rental_seed.bathrooms,
  null::integer,
  nullif(rental_seed.bed_type, ''),
  rental_seed.bathroom_type::public.bathroom_type,
  rental_seed.furnished,
  rental_seed.availability::public.availability_status,
  rental_seed.quantity_available,
  rental_seed.status::public.publish_status,
  rental_seed.sort_order,
  now(),
  now()
from rental_seed
join public.properties on properties.slug = rental_seed.property_slug
on conflict (property_id, slug) do update set
  title = excluded.title,
  internal_code = excluded.internal_code,
  variant = excluded.variant,
  room_type = excluded.room_type,
  description = excluded.description,
  price_min = excluded.price_min,
  price_max = excluded.price_max,
  currency = excluded.currency,
  price_note = excluded.price_note,
  bedrooms = excluded.bedrooms,
  bathrooms = excluded.bathrooms,
  bed_type = excluded.bed_type,
  bathroom_type = excluded.bathroom_type,
  furnished = excluded.furnished,
  availability = excluded.availability,
  quantity_available = excluded.quantity_available,
  status = excluded.status,
  sort_order = excluded.sort_order,
  published_at = coalesce(public.rental_options.published_at, excluded.published_at),
  updated_at = now();

commit;

-- Expected result after a clean import: 10 developments and 56 rental options.
select
  count(distinct properties.id) as imported_developments,
  count(rental_options.id) as imported_rental_options
from public.properties
left join public.rental_options on rental_options.property_id = properties.id
where properties.slug in ('the-zizz', 'residensi-suasana-damai', 'unio-residence-kepong', 'pixel-city-sentral', 'aratre-residences', 'high-park-suites', 'emporis-kota-damansara', 'meta-residence-seri-kembangan', 'rica-residence-sentul', 'platinum-splendor-semarak');
